export default {
    formItemLayout: {
        labelCol: { span: 24 },
        wrapperCol: { span: 24 },
    },
    institution: [{ required: true, message: "plese select" }],
    activeSummary: [{ required: true, message: "plese select" }],
    totalParticipants: [{ required: true, message: "plese input" }],
    totalMacaoParticipants: [{ required: true, message: "plese input" }],
    totalOverseasParticipants: [{ required: true, message: "plese input" }],
    participant: [{ required: true, message: "plese select" }],
    exTotalExhibitors: [{ required: true, message: "plese input" }],
    exTotalMacaoParticipants: [{ required: true, message: "plese input" }],
    exTotalOverseasParticipants: [{ required: true, message: "plese input" }],
    exParticipation: [{ required: true, message: "plese select" }],
    conventionDinings: [{ required: true, message: "plese input" }],
    totalSpeakers: [{ required: true, message: "plese input" }],
    speakers: [{ required: true, message: "plese input" }],
    totalDelegations: [{ required: true, message: "plese input" }],
    totalNoDelegations: [{ required: true, message: "plese input" }],
    totalHeadsOfDelegation: [{ required: true, message: "plese input" }],
    headsOfDelegations: [{ required: true, message: "plese input" }],
    promotionMarketingCost: [{ required: true, message: "plese input" }],
    translationCost: [{ required: true, message: "plese input" }],
    transportationCost: [{ required: true, message: "plese input" }],
    pcocost: [{ required: true, message: "plese input" }],
    openingCeremonyCost: [{ required: true, message: "plese input" }],
    venueRental: [{ required: true, message: "plese input" }],
    greenChannelCost: [{ required: true, message: "plese input" }],
    welcomeActivitiesCost: [{ required: true, message: "plese input" }],
};
